.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup, openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool, openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs, openebs-nativek8s/pipelines/stages/2-Infra-setup/storage-policies/openebs-sc, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool, openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall, openebs-nativek8s/utils/dump_cluster_state, openebs-nativek8s/utils/e2e-cr, openebs-nativek8s/utils/e2e-crd.yml, openebs-nativek8s/utils/e2e-result.yml, openebs-nativek8s/utils/error_handler, openebs-nativek8s/utils/event_updater, openebs-nativek8s/utils/generate_test_name, openebs-nativek8s/utils/get_litmus_result, openebs-nativek8s/utils/litmus_job_runner, openebs-nativek8s/utils/pooling, openebs-nativek8s/utils/result/result_update.py
- Creating the repository initial structure for pipeline stages.
=> refactor(repo): Creating repository structure for e2e-nativek8s branch

openebs-nativek8s/pipelines/stages/4-cleanup/cluster-cleanup/cluster-cleanup
=> refactor(repo): Added cluster cleanup job in nativek8s release branch cleanup stage

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup, openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool, openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs, openebs-nativek8s/pipelines/stages/2-Infra-setup/storage-policies/openebs-sc, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFS-volume-provision-percona/ZFS-volume-provision-percona, openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool, openebs-nativek8s/pipelines/stages/4-cleanup/cluster-cleanup/cluster-cleanup, openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall, openebs-nativek8s/utils/result/result_update.py
gitlab scripts for pipeline stages are added
- cluster state
- infra-setup (openebs deploy , striped pool , storage policies)
- functional (zfs pv provisioner , zfs volume proviision with percona application)
- cleanup
=> refactor(repo): Added jobs in nativek8s pipeline for release branch

openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup, openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool, openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFS-volume-provision-percona/ZFS-volume-provision-percona, openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool, openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall, openebs-nativek8s/utils/result/result_update.py
=> refactor(script): Adding set -x command in cluster-creation stage in nativek8s pipeline

openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs, openebs-nativek8s/pipelines/stages/4-cleanup/cluster-cleanup/cluster-cleanup
=> refactor(yaml): Modified the cluster cleanup stage in nativek8s pipeline

openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup, openebs-nativek8s/pipelines/stages/2-Infra-setup/create-striped-pool/create-striped-pool, openebs-nativek8s/pipelines/stages/2-Infra-setup/deploy-openebs/deploy-openebs, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFS-volume-provision-percona/ZFS-volume-provision-percona, openebs-nativek8s/pipelines/stages/4-cleanup/cleanup-spc-striped-pool/cleanup-spc-striped-pool, openebs-nativek8s/pipelines/stages/4-cleanup/cluster-cleanup/cluster-cleanup, openebs-nativek8s/pipelines/stages/4-cleanup/openebs-uninstall/openebs-uninstall
=> refactor(script): Added percona application deprovision after zfs-pv provision

openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner
- added zfs-driver-tag as a pipeline env
=> refactor(script): Modified zfspv-provisioner gitlab script to take zfs-driver as env

openebs-nativek8s/pipelines/stages/1-cluster-setup/cluster-setup, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-ext4/ZFS-vol-resize-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-xfs/ZFS-vol-resize-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize/ZFS-vol-resize, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-clone/ZFSPV-clone, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot/ZFSPV-snapshot
- Added test for volume properties verification set by storage class into the pipeline.
- This test is added in volume resize test pipeline script.
- Flow will be as below for all three (zfs, xfs and ext4) file system
- app_deploy
- zv_property_verify
- vol_resize
- app_deprovision
=> add(script): Add pipeline script for testing volume properties verification set via storage class 

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize/ZFS-vol-resize, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-ext4/ZV-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-xfs/ZV-property-modify-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify/ZV-property-modify
- Added zvolume property modify test into pipelines for all 3 file system ( zfs , xfs and ext4 )
=> add(script): Added pipeline script for zvolume properties modification test for zfs,ext4 and xfs

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-ext4/ZFSPV-snapshot-clone-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-xfs/ZFSPV-snapshot-clone-xfs
- resolved the path issue for zfspv snapshot and clone
- renamed jobname for creating e2e cr jobs
=> refactor(script): Resolved the issue in jobname mismatch in waiting e2ecr for clone test

openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner
- Added zfs_branch env in the zfs-localpv provisioner script.
- Referenced: https://github.com/openebs/e2e-tests/pull/247
=> refactor(script): Added zfs_branch env in sed command for deploying specific zfs-operator

openebs-nativek8s/pipelines/stages/4-upgrade/upgrade-zfslocalpv
=> fix(typo): fix typo in sed command

openebs-nativek8s/pipelines/stages/3-app-deploy/app-zfspv-snapshot-xfs, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize-ext4, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize-xfs, openebs-nativek8s/pipelines/stages/5-functional/zfspv-clone, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify-xfs
=> fix(script): Fixed the minor path/app_namespace errors in pipeline script

openebs-nativek8s/pipelines/stages/4-cleanup/cluster-cleanup/cluster-cleanup
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
=> fix[cluster-cleanup]: Modified the esx ip in cluster cleanup script

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-ext4/ZFS-vol-resize-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize-xfs/ZFS-vol-resize-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZFS-vol-resize/ZFS-vol-resize, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-ext4/ZFSPV-snapshot-clone-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-xfs/ZFSPV-snapshot-clone-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone/ZFSPV-snapshot-clone, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-ext4/ZV-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-xfs/ZV-property-modify-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify/ZV-property-modify
- Added pipeline script for zfspv-custom-topology test
- This job will run after zfs driver provision and High availability test.
- Accordingly modified the job pooling sequence.
=> new(Script): Added pipeline script for zfspv-custom-topology teest

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/ZFS-LocalPV-provisioner/ZFS-LocalPV-provisioner, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-raw-block-volume/ZFSPV-raw-block-volume
- Adding pipeline script for ZFSPV-raw-block-volume support e2e-test
Ref: https://github.com/openebs/e2e-tests/pull/350
=> new(script): Added pipeline script for raw-block-volume e2e-test

openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-custom-topology/ZFSPV-custom-topology, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-raw-block-volume/ZFSPV-raw-block-volume, openebs-nativek8s/pipelines/stages/4-infra-chaos/docker-restart/docker-restart, openebs-nativek8s/pipelines/stages/4-infra-chaos/kubelet-restart/kubelet-restart
- Resolved the path issue
- Modified sed command to take username `k8s`
=> refact(Script): Resolved the path issue in custom-topology test

openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-ext4/ZV-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-xfs/ZV-property-modify-xfs, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify/ZV-property-modify
- This PR changes pipline script according to the changes in the litmusbook here
https://github.com/openebs/e2e-tests/pull/433
- Modified the sed command to use file_system_type env value
=> [skip ci]: modified sed command to use file_system_type env

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/ZFSPV-snapshot-clone-btrfs/ZFSPV-snapshot-clone-btrfs, openebs-nativek8s/pipelines/stages/3-functional/ZV-property-modify-btrfs/ZV-property-modify-btrfs
- Adding following zfspv related test cases for btrfs file system
1. Snapshot and clone
2. Zvol property runtime modification
=> add(script): adding snapshot-clone and property modification test for btrfs fstype

openebs-nativek8s/pipelines/stages/2-zfs-localpv-provisioner/zfs-localpv-provisioner
- modified sed command to take os_name and zpool_creation values as env
=> refact(script): modified sed command to take os_name as env

openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify-ext4, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify-xfs
- modified sed command to take fsype as env
=> refact(script): add fstype env in sed command

.gitlab-ci.yml
-  modified the gitlab ci yaml
=> [skip ci]: modified the gitlab ci yaml

.gitlab-ci.yml
- modify the gitlab ci yaml file
=> [skip ci]: modify the gitlab ci yaml file

openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner, openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability, openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify, openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume, openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs, openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs, openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs, openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create, openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs, openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs, openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs, openebs-nativek8s/utils/result/result_update.py
- fixed the path issue in python script for updating the pipeline test result
=> [skip ci]: fixed the path issue for updating test result

openebs-nativek8s/utils/result/result_update.py
- Removing the kibana logs link from the result update script.
=> refact(script): remove the kibana logs link from result update script

stages/1-cluster-setup/1S01-cluster-setup/README.md
- removing the dummy job results
=> chore(readme): removing the dummy job result

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/2-provisioner/2P01-zfs-localpv-provisioner, openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability, openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify, openebs-nativek8s/pipelines/stages/3-functional/3F02-zfspv-raw-block-volume, openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs, openebs-nativek8s/pipelines/stages/3-functional/3F06-zfspv-property-modify-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F07-zfspv-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F08-zfspv-property-modify-xfs, openebs-nativek8s/pipelines/stages/3-functional/3F09-zfspv-property-modify-btrfs, openebs-nativek8s/pipelines/stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create, openebs-nativek8s/pipelines/stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create, openebs-nativek8s/pipelines/stages/3-functional/3F14-zfspv-shared-mount-volume-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F15-zfspv-shared-mount-volume-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F16-zfspv-shared-mount-volume-xfs, openebs-nativek8s/pipelines/stages/5-infra-chaos/5I01-node-docker-restart-zfs, openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs
- fixing the date issue in result update script
=> [skip ci]: fixing the date issue in result update script

openebs-nativek8s/pipelines/stages/2-provisioner/2P02-zfs-controller-high-availability, openebs-nativek8s/pipelines/stages/5-infra-chaos/5I02-node-kubelet-restart-zfs
- gittoken env was missing from the script, so result was not updating. this PR fixes that issue
=> [skip ci]: fixed the missing gittoken issue

openebs-nativek8s/pipelines/stages/2-zfs-localpv-provisioner/zfs-controller-HA, openebs-nativek8s/pipelines/stages/2-zfs-localpv-provisioner/zfs-localpv-provisioner, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zfspv-snapshot, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zfspv-snapshot-ext4, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zfspv-snapshot-xfs, openebs-nativek8s/pipelines/stages/4-upgrade/upgrade-zfslocalpv, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize-ext4, openebs-nativek8s/pipelines/stages/5-functional/zfs-vol-resize-xfs, openebs-nativek8s/pipelines/stages/5-functional/zfspv-clone, openebs-nativek8s/pipelines/stages/5-functional/zfspv-clone-ext4, openebs-nativek8s/pipelines/stages/5-functional/zfspv-clone-xfs, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify-ext4, openebs-nativek8s/pipelines/stages/5-functional/zv-property-modify-xfs
- modified the test paths to accommodate latest changes
=> [skip ci]: modified the test paths to accommodate latest changes

README.md, stages/1-cluster-setup/1S01-cluster-setup/README.md, stages/2-provisioner/2P01-zfs-localpv-provisioner-deploy/README.md, stages/2-provisioner/2P02-zfs-controller-high-availability/README.md, stages/3-functional/3F01-zfspv-custom-topology-verify/README.md, stages/3-functional/3F02-zfspv-raw-block-volume/README.md, stages/3-functional/3F03-zfs-volume-resize-zfs/README.md, stages/3-functional/3F04-zfs-volume-resize-ext4/README.md, stages/3-functional/3F05-zfs-volume-resize-xfs/README.md, stages/3-functional/3F06-zfspv-property-modify-zfs/README.md, stages/3-functional/3F07-zfspv-property-modify-ext4/README.md, stages/3-functional/3F08-zfspv-property-modify-xfs/README.md, stages/3-functional/3F09-zfspv-property-modify-btrfs/README.md, stages/3-functional/3F10-zfspv-snapshot-clone-zfs-create/README.md, stages/3-functional/3F11-zfspv-snapshot-clone-ext4-create/README.md, stages/3-functional/3F12-zfspv-snapshot-clone-xfs-create/README.md, stages/3-functional/3F13-zfspv-snapshot-clone-btrfs-create/README.md, stages/3-functional/3F14-zfspv-shared-mount-volume-zfs/README.md, stages/3-functional/3F15-zfspv-shared-mount-volume-ext4/README.md, stages/3-functional/3F16-zfspv-shared-mount-volume-xfs/README.md, stages/5-infra-chaos/5I01-node-docker-restart-zfs/README.md, stages/5-infra-chaos/5I02-node-kubelet-restart-zfs/README.md
- Fixed the issue in link which forwards to the readme in e2e-tests repo
=> [skip ci]: fixed the link to the readme to e2e-tests repo

openebs-nativek8s/pipelines/stages/6-cleanup/6D01-cluster-cleanup
- Changed the VM names in the cluster cleanup stage to accommodate the latest changes in vm_names.
=> change(vars): change the vm names for cleanup script

openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify-xfs
- Fixed the path issue in test for upgrade branch.
=> [skip ci]: fixed the path issue in upgrade branch

openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify-ext4, openebs-nativek8s/pipelines/stages/3-app-deploy/app-zv-property-modify-xfs, openebs-nativek8s/pipelines/stages/6-cleanup/cluster-cleanup/cluster-cleanup
- Added the configmap values for data consistency check
- changed the vm names for cluster cleanup stage
=> Added the configmap values for data consistency check

stages/4-chaos/4C01-app-pod-kill-zfs/README.md, stages/4-chaos/4C02-app-pod-kill-xfs/README.md, stages/4-chaos/4C03-app-pod-kill-ext4/README.md, stages/4-chaos/README.md
- This PR adds chaos stage readme files for updating the gitlab job results.
=> [skip ci]: adding readme file for chaos stage

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/4-chaos/4C01-app-pod-kill-zfs, openebs-nativek8s/pipelines/stages/4-chaos/4C02-app-pod-kill-xfs, openebs-nativek8s/pipelines/stages/4-chaos/4C03-app-pod-kill-ext4
- This PR adds the chaos stage in nativek8s pipeline.
- For chaos stage this PR adds application pod kill test for zfs, xfs and ext4 file system.
=> [skip ci]: Application pod kill chaos test added in nativek8s pipeline

openebs-nativek8s/pipelines/stages/4-chaos/4C01-app-pod-kill-zfs, openebs-nativek8s/pipelines/stages/4-chaos/4C02-app-pod-kill-xfs, openebs-nativek8s/pipelines/stages/4-chaos/4C03-app-pod-kill-ext4
- fixed the path issue in sed command
=> [skip ci]: fixed the path issue in sed command

stages/5-infra-chaos/5I03-node-failure-zfs/README.md, stages/5-infra-chaos/README.md
- This PR adds the readme file for node failure infra-chaos to update the gitlab pipeline test results.
=> [skip ci]: add readme file for node failure infra chaos

openebs-nativek8s/pipelines/stages/5-infra-chaos/5I03-node-failure-zfs
- This PR fixes the env for node password secret
=> fix(env): fixed the env name of secret value for node-password

stages/3-functional/3F17-zfspv-shared-mount-volume-btrfs/README.md, stages/3-functional/README.md, stages/4-chaos/4C04-app-pod-kill-btrfs/README.md, stages/4-chaos/README.md
- This PR add readme file for following tests for btrfs file-system
1. Shared-mount-volume for btrfs
2. App-pod-failure for btrfs
=> [skip ci]: Add readme file for shared mount and pod restart for btrfs

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/3F17-zfspv-shared-mount-volume-btrfs, openebs-nativek8s/pipelines/stages/4-chaos/4C04-app-pod-kill-btrfs
- This PR adds following tests related to btrfs file system into pipeline.
1. Shared-mount-volume for btrfs
2. App-pod-failure for btrfs
=> [skip ci]: Add shared volume and pod restart test for btrfs

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns
- This PR adds e2e-pipeline gitlab script for backup and restore test cases.
- Here in gitlab-ci yaml file we split Functional stage in two parts, so that one stage does not look very long in UI of gitlab page.
=> [skip ci]: backup and restore e2e-pipelines script

openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns
- fixed the label issue to maintain different labels for different jobs.
=> refact(script): fixed the label issue in backup restore script

openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns
- fixed the env to create velero restore.
=> [skip ci]: fixed the env to create velero restore

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
- This PR adds pipeline script for e2e -test  of zfspv cloning directly from pvc.
- This test case has been added with three file-systems zfs,xfs,and ext4
=> feat(script): Add pipeline script for e2e test of zfspv clone directly from pvc

.gitlab-ci.yml, openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node
- This PR adds pipeline scripts for e2e-test of restoring on different nodes for zfs-localpv
- This test has been added with three file-system (zfs,ext4 and xfs)
=> add(script): add pipeline script for restore on different node test

openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
=> [skip ci]: fixed the sed commands

openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
=> fix(script): fixed the deprovision script

openebs-nativek8s/pipelines/stages/3-functional/3F24-zfspv-clone-from-pvc-zfs, openebs-nativek8s/pipelines/stages/3-functional/3F25-zfspv-clone-from-pvc-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F26-zfspv-clone-from-pvc-xfs
- This PR fixes the label mismatch in parent application pod and cloned application pod
=> refact(script): add new env's and value in the pipeline script

.gitlab-ci.yml
=> refact(yaml): fixed the gitlab-ci yaml file

openebs-nativek8s/utils/litmus_job_runner
- After creating job sometimes litmus pod takes time to schedule, so adding retry loop to detect litmus pod name
=> refact(script): add retries loop to detect litmus pod name

openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node
=> fix(script): Fixed the execution order for backup restore jobs

openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F30-zfs-incremental-backup-restore
- Adding application pod deprovision task at end of e2e-tests to save resources for next jobs
=> refact(script): add app-deprovision tasks at end of e2e-test

openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F30-zfs-incremental-backup-restore
=> refact(script): fixed the typo in backup restore test-casses

openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F30-zfs-incremental-backup-restore
=> fix(typo): fixed typo in gitlab script

openebs-nativek8s/pipelines/stages/3-functional/3F04-zfs-volume-resize-ext4, openebs-nativek8s/pipelines/stages/3-functional/3F05-zfs-volume-resize-xfs, openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F21-zfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F22-ext4-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F23-xfs-backup-restore-same-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F30-zfs-incremental-backup-restore
=> refact(script): Add deprovision of restored application

openebs-nativek8s/pipelines/stages/3-functional/3F18-zfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F19-ext4-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F20-xfs-backup-restore-diff-ns, openebs-nativek8s/pipelines/stages/3-functional/3F27-zfs-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F28-ext4-backup-restore-diff-node, openebs-nativek8s/pipelines/stages/3-functional/3F29-xfs-backup-restore-diff-node
=> fix(typo): fixed typo in exit condition in restore pipeline script

.gitlab-ci.yml
=> fix(yaml): fixed the syntax error in gitlab-ci yaml

pipeline/stages/6-cleanup/6D01-cluster-cleanup, pipeline/utils/lvm-e2e-result.yml
=> fix(crd): fix the apiversion field in lvm-e2e-result

pipeline/stages/2-provisioner/2P01-lvm-localpv-provisioner, pipeline/utils/e2e_job_runner, pipeline/utils/pooling
=> fix(yaml): fixed the cr name in pooling job util

pipeline/stages/2-provisioner/2P01-lvm-localpv-provisioner, pipeline/stages/6-cleanup/6D01-cluster-cleanup
=> fix(script): fixed the esx ip in cluster cleanup stage

pipeline/stages/3-functional/3F01-lvm-volume-resize
=> fix(e2er): fixed the application namespace syntax error for e2e-cr

openebs-nativek8s/pipelines/stages/3-functional/3F01-zfspv-custom-topology-verify, openebs-nativek8s/pipelines/stages/3-functional/3F03-zfs-volume-resize-zfs
- change the order of job execution to make best use of pipeline cluster resources
=> refact(yaml): change the order of jobs execution

pipeline/stages/4-chaos/4C01-application-pod-failure, pipeline/stages/5-infra-chaos/5I01-node-docker-restart, pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart, pipeline/stages/5-infra-chaos/5I03-node-power-failure
=> refact(yaml): fixed the error in updating e2e-cr

pipeline/stages/4-chaos/4C01-application-pod-failure, pipeline/stages/5-infra-chaos/5I01-node-docker-restart, pipeline/stages/5-infra-chaos/5I02-node-kubelet-restart, pipeline/stages/5-infra-chaos/5I03-node-power-failure
=> refact(script): fix the syntax error in e2e-cr

pipeline/stages/2-provisioner/2P01-lvm-localpv-provisioner
=> refact(script): fixed the lvm-nodes list env

pipeline/stages/5-infra-chaos/5I03-node-power-failure
=> fix(path): fixed the path in node_failure test directory

pipeline/stages/5-infra-chaos/5I03-node-power-failure
Reverts mayadata-io/e2e-nativek8s#97
=> Revert "fix(path): fixed the path in node_failure test directory"

.gitlab-ci.yml, pipeline/stages/3-functional/3F01-lvm-volume-resize, pipeline/stages/3-functional/3F02-lvm-volume-resize-xfs, pipeline/stages/3-functional/3F03-lvm-volume-resize-btrfs, pipeline/stages/3-functional/3F04-lvmpv-custom-topology, pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lmvpv-shared-mount-volume-btrfs, pipeline/stages/3-functional/3F08-lmvpv-snapshot-ext4, pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs, pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs
- Add pipeline script for lvmpv-e2e-tests
=> add(script): Add pipeline script for lvmpv-e2e-tests

pipeline/stages/3-functional/3F04-lvmpv-custom-topology, pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs, pipeline/stages/3-functional/3F08-lvmpv-snapshot-ext4, pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs, pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs
=> fix(path): fixed the ssh path to lvm-pipeline cluster

pipeline/stages/3-functional/3F04-lvmpv-custom-topology, pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs
=> fix(path): fixed the path to run the e2e-jo

pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs
=> fix(path): fixed the typo in the e2e-job label

pipeline/stages/3-functional/3F05-lvmpv-shared-mount-volume-ext4, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs
=> fix(script): fixed the typo in e2e-cr

.gitlab-ci.yml, pipeline/stages/3-functional/3F03-lvm-volume-resize-btrfs, pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs, pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs, pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs
- pipeline script for e2e-test of resize for lvm-volume when fstype is btrfs
=> add(script): Pipeline script for lvm-volume resize for btrfs file system

pipeline/stages/3-functional/3F06-lvmpv-shared-mount-volume-xfs, pipeline/stages/3-functional/3F07-lvmpv-shared-mount-volume-btrfs, pipeline/stages/3-functional/3F09-lvmpv-snapshot-xfs, pipeline/stages/3-functional/3F10-lvmpv-snapshot-btrfs
=> fix(script): fix sed_command in job runner file
